// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("ac1ce8f6-dd02-4413-85a7-1f099df221ad")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("Markov.Tests")]
