// <auto-generated />
using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Markov")]
[assembly: AssemblyDescription("A Markov chain library, made to support scenarios anywhere from text generation to stock market simulation.")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("John Gietzen")]
[assembly: AssemblyProduct("Markov")]
[assembly: AssemblyCopyright("Copyright © John Gietzen 2011")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

[assembly: CLSCompliant(true)]

[assembly: ComVisible(false)]

[assembly: Guid("ac1ce8f6-dd02-4413-85a7-1f099df221ad")]

[assembly: AssemblyVersion("1.2.0")]
[assembly: AssemblyFileVersion("1.2.0")]
